@echo off
echo Deleting old venv...
rmdir /s /q venv
echo Creating new venv...
python -m venv venv
echo Activating venv...
call venv\Scripts\activate
echo Installing packages...
pip install gradio openrouter requests python-dotenv
echo Done!
echo Run: python app.py
pause